version: "3"

services:
    navyt:
        build: .
        network_mode: bridge
        image: navyt:${tag:-latest}
        container_name: navyt_${tag:-latest}

        ports:
            - "127.0.0.1:9098:9098"

        volumes:
            - /tmp/log/navyg:/tmp/log/navyg
            - /Users/navygong/work/go/src/mine/k8s/config.toml:/go/src/navyt/config.toml

        command:
            ["/usr/bin/navyt", "run", "config.toml"]
